name: LandsPlugin
version: '${project.version}'
main: com.thatsoulyguy.landsplugin.LandsPlugin
api-version: '1.20'

depend: [Multiverse-Core]

commands:
  hub:
    description: Hub-a-dub-dub
    aliases:
      - hb
      - h
      - lobby
      - lby
      - ly
      - l

  lands:
    description: Landn' deez, nutz'!
    aliases:
      - land
      - ld
      - l